### ISSUE TITLE
Some remarks to readme

### ISSUE THREAD

**Issue by weselow** [NeedsCoffee/Tailscale-Updater-Windows#2]
I suggest to add some remarks to readme about installation process.

First of all, allow PowerShell scripts to be executed.
I set policy Undefined, you can choose your own. More detais about policy can be found [here at microsoft](https://docs.microsoft.com/ru-ru/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1))
```
 Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope LocalMachine
 Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser
```

Using one-line-command installation I had to set in PowerShell TLS version first. 
Overwise, it causes an error `The request was aborted: Could not create SSL/TLS secure channel.`.
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

**Comment by NeedsCoffee** [comment]
Thanks for this. TLS 1.2 bit added to one-liner for v0.3.0

**Comment by NeedsCoffee** [comment]
Execution policy now added to one-liner.
